# Generated by Django 3.0.2 on 2021-02-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=5000)),
                ('rel_date', models.DateField()),
                ('avg_rating', models.FloatField()),
            ],
        ),
    ]
